import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import SessionProvider from "../utils/SessionProvider";

export const metadata: Metadata = {
  title: "Deneme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = getServerSession();

  return (
    <html lang="en" className="bg-white">
      <body>
        <SessionProvider session={session}>
        <div className="container mx-auto px-4">
          <Navbar/>
          {children}
        </div>
        </SessionProvider>
      </body>
    </html>
  );
}
